version: "3.8"

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: whizlabs
    networks:
      webapp:
        ipv4_address: 192.168.0.2
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  web:
    build:
      context: ./nodeApp
      dockerfile: Dockerfile
    container_name: nodeapp
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      webapp:
        ipv4_address: 192.168.0.3
    restart: unless-stopped
    environment:
      DB_HOST: 192.168.0.2
      DB_USER: root
      DB_PASS: whizlabs
      DB_NAME: company

volumes:
  mysql-data:

networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
