apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: webapp
spec:
  ClusterIP: None
  ports:
    - name: mysql-tcp
      port: 3306
      protocol: TCP
      containerPort: 3306
  selector:
    app: mysql 