apiVersion: v1
kind: Service
metadata:
  name: node-web-svc
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: node-web
    version: blue  # Initially points to blue
  ports:
    - port: 80
      targetPort: 3000
