name: Docker Build (CI)

on:
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Testing
        run: |
          ls -la

      # - name: Login to Azure Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.ACR_LOGIN_SERVER }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Build docker image
      #   run: |
      #     docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:ci .

      # - name: Push docker image
      #   run: |
      #     docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:ci
