name: Docker Build (CI)

on:
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4
        
      # List files for debugging purposes
      - name: Testing
        run: |
          ls -la

      # Log in to Azure Container Registry using secrets
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build the Docker image and tag it with the commit SHA and v1
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/node:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/node:v1 .

      # Push the Docker image to Azure Container Registry
      - name: Push docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node:v1
