name: Docker Build (CI)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4
        
      # List files for debugging purposes
      - name: Testing
        run: |
          ls -la

      # Log in to Azure Container Registry using secrets
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build the Docker image and tag it with the commit SHA and v1
      # Build and push Node.js Docker image
      - name: Build and push Node.js image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:v1 -f nodeApp/Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:v1

      # Build and push MySQL Docker image
      - name: Build and push MySQL image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/mysql:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/mysql:v1 -f mysql/Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/mysql:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/mysql:v1
